---

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'
  - react
  - import
  - 'jsx-a11y'

env:
  node: true
  browser: true

extends:
  - airbnb-typescript
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended

rules:
  no-console: 0
  react/prop-types: 0
