---

plugins:
  - babel
  - react
  - import
  - 'jsx-a11y'

env:
  node: true
  browser: true

parser: babel-eslint

extends:
  - airbnb
  - plugin:react/recommended
  - "plugin:react-hooks/recommended"

rules:
  no-console: 0
  react/prop-types: 0
